name: API Codegen

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC to check for API changes
    - cron: '0 2 * * *'

jobs:
  generate-api-client:
    name: Generate API Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate API client
        run: yarn generate:api

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain src/api/generated) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update API client from OpenAPI spec'
          title: 'Update API Client'
          body: |
            ## API Client Update

            This PR updates the generated API client based on the latest OpenAPI specification from the BFF service.

            ### Changes
            - Updated API endpoints
            - Updated request/response types
            - Generated React Query hooks

            Please review the changes and merge if everything looks correct.
          branch: api-client-update
          delete-branch: true
